---
galaxy_info:
  author: Ideus team
  description: A role for installing Nagios 4
  min_ansible_version: 1.4
  version: 0.0.1
  license: ISC
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
    - system
    - monitoring

