

- name: Include postgresql command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_pgsql]=/usr/lib/nagios/plugins/check_pgsql -H localhost -d expman_production -l expman -p secret'
    present=true

- name: Include elasticsearch command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_elasticsearch_cluser]=/usr/lib/nagios/plugins/check_elasticsearch_cluster.rb --ip 107.170.106.199 --port 9200'
    present=true

- name: Include unicorn1 command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_unicorn]=/usr/lib/nagios/plugins/check_unicorn 2'
    present=true

- name: Include unicorn2 command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_unicorn_processes]=/usr/lib/nagios/plugins/check_unicorn_processes 2'
    present=true

- name: Include nginx command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_nginx_status]=sudo /usr/lib/nagios/plugins/check_nginx_status.sh IP 80 nginx_status'
    present=true

- name: Include check_disk command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_disk]=/usr/lib/nagios/plugins/check_disk -w 10% -c 5% -p /'
    present=true

- name: Include check_load command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_load_nrpe]=/usr/lib/nagios/plugins/check_load -w 5.0,4.0,3.0 -c 10.0,6.0,4.0'
    present=true

- name: Include check_procs command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_procs_nrpe]=/usr/lib/nagios/plugins/check_procs -w 10 -c 20 --metric CPU'
    present=true

- name: Include check_http command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_http_nrpe]=/usr/lib/nagios/plugins/check_http -H IP'
    present=true

- name: Include check_ssh command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_ssh_nrpe]=/usr/lib/nagios/plugins/check_ssh IP'
    present=true

- name: Include check_ping command
  sudo: true
  lineinfile: >
    dest=/etc/nagios/nrpe.cfg
    regexp='' 
    insertafter=EOF
    line='command[check_ping_nrpe]=/usr/lib/nagios/plugins/check_ping -H IP -w 100.0,20% -c 500.0,60%'
    present=true